name: Java CI with Gradle

on:
  push:
    branches:
     -main
     -dev
     -be/dev


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'zulu'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Docker build
        run: |
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker build -t seb45-13-main . 
          docker tag seb45-13-main mikiri611/seb45-13-main:${GITHUB_SHA::7}
          docker push mikiri611/seb45-13-main:${GITHUB_SHA::7}